// <auto-generated />
using System;
using Localize.Company.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Localize.Company.Infrastructure.Migrations
{
    [DbContext(typeof(LocalizeCompanyContext))]
    partial class LocalizeCompanyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Localize.Company.Domain.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Abertura")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("AtividadePrincipal")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("NaturezaLegal")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NomeEmpresarial")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Localize.Company.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Localize.Company.Domain.Entities.Organization", b =>
                {
                    b.HasOne("Localize.Company.Domain.Entities.User", null)
                        .WithMany("Organizations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Localize.Company.Domain.Entities.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<int>("OrganizationId")
                                .HasColumnType("int");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Complemento")
                                .IsRequired()
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Rua")
                                .IsRequired()
                                .HasColumnType("varchar(255)");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("Organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.Navigation("Endereco")
                        .IsRequired();
                });

            modelBuilder.Entity("Localize.Company.Domain.Entities.User", b =>
                {
                    b.Navigation("Organizations");
                });
#pragma warning restore 612, 618
        }
    }
}
